### ISSUE TITLE
Vary time cutoff

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#10]
We need to be able to vary the time cutoff for both accessibility and isochrones. We can now quickly calculate isochrones are arbitrary cutoffs, we just need to connect it to the UI.

**Comment by trevorgerhardt** [comment]
I'm going to build this with a `<select>` for now. Sliders are finnicky and I'd like to stay away from them as much as possible. Increments of 5 minutes to start.

**Comment by mattwigway** [comment]
OK. We could also do a <- 60 -> type button (where <- and -> are -/+ 5
minutes respectively).

On Mon, Jan 4, 2016 at 8:10 PM, Trevor Gerhardt <notifications@github.com>
wrote:

> I'm going to build this with a <select> for now. Sliders are finnicky and
> I'd like to stay away from them as much as possible. Increments of 5
> minutes to start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/taui/issues/10#issuecomment-168891168>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by trevorgerhardt** [comment]
It's mostly the styling/interaction. Selects are much simpler.

**Comment by mattwigway** [comment]
Yep! I wasn't objecting, just stating another possibility.

On Mon, Jan 4, 2016 at 8:34 PM, Trevor Gerhardt <notifications@github.com>
wrote:

> It's mostly the styling/interaction. Selects are much simpler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/taui/issues/10#issuecomment-168893862>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by mattwigway** [comment]
One thing we should do (although it doesn't have to happen right away) is to have a smooth transition when changing the cutoff, e.g. changing from 60 minutes to 30 minutes should animate the isochrone through all (or some, depending on speed) of the isochrones between 30 and 60 minutes.

**Comment by trevorgerhardt** [comment]
Ugh. The React flow does not play nice with Leaflet. Updates are taking way longer in Taui then they should.

**Comment by trevorgerhardt** [comment]
Works as a select button for now.
