### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by abyrd** [conveyal/taui#107]
We should probably call this `analysis-static-ui`.

**Comment by trevorgerhardt** [comment]
If we drop the fact that `taui` is an acronym then I think this is just a fun name for a project and much easier to refer to than `analysis-static-ui`.

**Comment by abyrd** [comment]
In that case we just need to make sure we're not referring to anything else as TAUI - I had the impression there were references to it elsewhere. The name is more fun and shorter, for sure. I was just thinking the naming scheme analysis-backend, analysis-ui, analysis-static-ui groups together these related projects.

**Comment by landonreed** [comment]
static-analysis-ui (SAUI)?  Somewhat distinguishes it from the others (by putting static in front), but still places it in the same family if we spell it out.  Plus, we get another fun-sounding name and a name that makes a little more sense for the project.

**Comment by abyrd** [comment]
Good proposal @landonreed but I'm not sure it's worth the effort and adaptation to change one letter.

**Comment by landonreed** [comment]
This is true.
