### ISSUE TITLE
Accessibility display is broken

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#11]
It always says "0 jobs" even though I can see the mutator occurring that is supposed to change the number:

![image](https://cloud.githubusercontent.com/assets/566958/12056251/375bee86-aee9-11e5-982d-c04a1e9adb9a.png)

![image](https://cloud.githubusercontent.com/assets/566958/12056258/4c2951f0-aee9-11e5-98dd-3a10fda3c009.png)

**Comment by trevorgerhardt** [comment]
I'm pretty sure the display is now fixed, but Browsochrones is no longer calculating accessibility correctly. Getting 0 every time. Even in the BS demo.

**Comment by mattwigway** [comment]
OK, I'll look into that today.
