### ISSUE TITLE
Put accessibility breakdown into cards

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#20]
Let's put separate accessibility breakdowns for new and old routes into cards, so that clicking on them can change which isochrone is displayed on the map.

**Comment by trevorgerhardt** [comment]
Ok, so instead of showing the % diff we just show the totals? I'm all for it, more of a contained breakdown of the old vs new

**Comment by mattwigway** [comment]
I'm thinking we put the percent change in the new system card. So the new system card would contain totals and percent change, and the old system card would just contain totals.

**Comment by trevorgerhardt** [comment]
Breakdown is in the cards!
