### ISSUE TITLE
Route names on map don't match those on cards

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#22]
![image](https://cloud.githubusercontent.com/assets/566958/13684915/facdf722-e6db-11e5-9723-7a0e559d6a77.png)

**Comment by trevorgerhardt** [comment]
The code for showing the route names is pretty simple and uses the same transitive data. It doesn't look like I'm doing anything strange, want to take a look?

https://github.com/conveyal/taui/blob/master/src/components/route-card.js#L57

**Comment by trevorgerhardt** [comment]
```js
function extractRelevantTransitiveInfo ({journeys, patterns, routes, stops}) {
  return journeys
    .map(j => {
      return j.segments
        .filter(s => !!s.pattern_id)
        .map(s => {
          const seg = {}
          const route = routes[parseInt(patterns[parseInt(s.pattern_id, 10)].route_id, 10)]
          const color = Color(`#${route.route_color}`)
          seg.name = route.route_long_name
          seg.backgroundColor = color.rgbaString()
          seg.color = color.light() ? '#000' : '#fff'
          seg.type = typeToIcon[route.route_type]

          return seg
        })
    })
}
```

**Comment by mattwigway** [comment]
The routes array is not indexed by route ID, to find a particular route you have to do routes.find(r => r.route_id === desiredRouteId). Same with patterns.
