### ISSUE TITLE
Geocoder box text stays present after clearing field

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#23]
When you click in the origin or destination field after already having entered information in the geocoder, the text is not cleared visually, although it is evidently cleared from the component, as pressing enter does nothing until a new address has been entered.

**Comment by trevorgerhardt** [comment]
How would I reproduce this problem?

**Comment by mattwigway** [comment]
Perform an origin/destination search, then click in the geocoder again as if to perform another search. Note that while the text is not cleared, the box behaves as if it is empty.

**Comment by trevorgerhardt** [comment]
It's not clear to me what the problem is. You can click the "x" to clear the box or click inline (not the clear button) and the text stays but it allows you to start typing a new address.
