### ISSUE TITLE
Negative signs on increases in travel time

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#24]
If we're saying "slower" we don't need to put the sign of the change in the app:

![image](https://cloud.githubusercontent.com/assets/566958/13745171/ee22e412-e9c2-11e5-9f0d-293b1988ae10.png)

**Comment by trevorgerhardt** [comment]
Fixed in 2016fb7d0d72713fb3d8b8f6b920d7a3c5c5dd6a
