### ISSUE TITLE
Isoline issue

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#25]
![image](https://cloud.githubusercontent.com/assets/566958/13745205/2f13a74a-e9c3-11e5-859b-69b425be189a.png)

Probably a bug in conveyal/jsolines

**Comment by mattwigway** [comment]
Yep, upstream (using IndyConnect-marion):

![image](https://cloud.githubusercontent.com/assets/566958/13745300/ab83a1b8-e9c3-11e5-8e30-68048ba2c03d.png)

**Comment by mattwigway** [comment]
Also, the extension to the right stretches all the way to the right edge of the world.

**Comment by trevorgerhardt** [comment]
the edge of the world :scream:

**Comment by mattwigway** [comment]
Seems like this might be the problem:

![image](https://cloud.githubusercontent.com/assets/566958/13745554/138d927c-e9c5-11e5-9350-34dde7921a1b.png)

**Comment by mattwigway** [comment]
Yeah at the edge of the graph it's trying to do linear interpolation when the values aren't changing, so the fraction denominator is 0. Don't divide by zero.

**Comment by trevorgerhardt** [comment]
Oi, Infinity degrees longitude really is the edge of the world
