### ISSUE TITLE
Geocoder results in Indianapolis

### ISSUE THREAD

**Issue by mattwigway** [conveyal/taui#30]
The geocoder results in Indianapolis are not up to snuff. For example, our default address of 111 Monument Circle, Indianapolis, IN becomes 111 Monument Circle, Center, IN (using township name rather than city name). This is an upstream issue in Pelias: pelias/pelias#184. However, we do need to fix it ASAP for our deployment, maybe just switch back to Mapbox geocoding?

**Comment by trevorgerhardt** [comment]
Fixed
