### ISSUE TITLE
Lat/lng representation

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/taui#8]
GeoJSON uses `coordinates` in the form of: `[${longitude}, ${latitude}]`.
Leaflet uses `latlng` in the form of: `{ lat: ${latitude}, lng: ${longitude} }` ... along with a few others.
`turf-point` is a GeoJSON `Feature` object using `coordinates`.

Pfft. Create a helper that normalizes this?

**Comment by mattwigway** [comment]
https://twitter.com/tmcw/status/598605684477943808

**Comment by trevorgerhardt** [comment]
I'm going to create a helper, but it's going to be based on variable/function names.

Rules:

1. Anything named `coordinates` will look like `[${longitude}, ${latitude}]`
2. Anything named `latlng` will look like `{ lat:${latitude},lng:${longitude} }`. 
3. The reverse `[${lat}, ${lng}]` SHALL NEVER BE USED.
4. The shorthand `lon` SHALL NEVER BE USED.
5. If the reverse or lon need to be used for external libs, never store in a variable, convert on input/output.

**Comment by mattwigway** [comment]
Sounds good. It may take a while for me to get into the habit of writing
lng instead of lon but I'll do my best. Completely agreed that it should
always be [longitude, latitude].

On Wed, Dec 30, 2015 at 8:57 PM, Trevor Gerhardt <notifications@github.com>
wrote:

> I'm going to create a helper, but it's going to be based on
> variable/function names.
>
> Rules:
>
>    1. Anything named coordinates will look like [${longitude},
>    ${latitude}]
>    2. Anything named latlng will look like {
>    lat:${latitude},lng:${longitude} }.
>    3. The reverse [${lat}, ${lng}] SHALL NEVER BE USED.
>    4. The shorthand lon SHALL NEVER BE USED.
>    5. If the reverse or lon need to be used for external libs, never
>    store in a variable, convert on input/output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/taui/issues/8#issuecomment-168125405>.
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by trevorgerhardt** [comment]
x/y should be called `point`s and should be an object. `point.x`, `point.y`. So...

`originCoordinate` should look like `[70.01232, 38.13234]`
`originLatLng` should look like `{ lat: 38.13234, lng: 70.01232 }`
`originPoint` should look like `{ x: 70.01232, y: 38.13234 }`

These rules need to be followed for function inputs and return values and object properties but not 100% necessary if contained.

**Comment by trevorgerhardt** [comment]
Added ll.js, to be abstracted out on it's own at a later date.
